[project]
name = "renpy"
readme = "README.rst"
license = "MIT"
dynamic = ["version"]
requires-python = "==3.12.10"
dependencies = [
    "future",
    "six",
    "pefile",
    "requests",
    "ecdsa",
    "pygame_sdl2 @ git+https://github.com/Andykl/pygame_sdl2.git@uv-build",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "cython",
    "setuptools",

]

[build-system]
requires = [
    "setuptools",
    "cython",
    "pygame_sdl2 @ git+https://github.com/Andykl/pygame_sdl2.git@uv-build",
]

[tool.pyright]
include = ["*.py", "renpy/", "src/"]
exclude = ["module/build/"]
ignore = ["renpycoverage.py"]

reportOptionalSubscript = false
reportOptionalMemberAccess = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalContextManager = false
reportOptionalOperand = false
reportMissingModuleSource = false

[tool.cyright]
include = ["*.py", "renpy/", "src/"]
exclude = ["module/build/"]
ignore = ["renpycoverage.py"]

reportGeneralTypeIssues = false
reportOptionalSubscript = false
reportOptionalMemberAccess = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalContextManager = false
reportOptionalOperand = false
reportMissingModuleSource = false

[tool.ruff]
line-length = 120

[tool.ruff.format]
preview = true
